### ISSUE TITLE
Error: Cannot find module 'merge-stream'

### ISSUE THREAD

**Issue by charlievoss** [iDev0urer/salesforce-angular2-boilerplate#4]
Really want to get this working but keep running into same error:

Error: Cannot find module 'merge-stream'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

After researching issue have used npm clear cache and re-installing gulp but error persists.

**Comment by watzon** [comment]
Hmm, try `npm install --save-dev merge-stream`. I'll check the package.json and make sure it's where it should be

**Comment by watzon** [comment]
@charlievoss Just added it. Let me know if that solves your problems.

**Comment by charlievoss** [comment]
Thank you.  

I completely removed the project and started with a new clone ... now receiving new errors ...

Despite the fact that I can clearly see it within node_modules, now receiving the error Cannot find module 'crypto-js', after which terminal also shows Cannot find module './keys.pipe'

Finally and fatally at the end is Error: Cannot find module 'express'.

**Comment by watzon** [comment]
@charlievoss when are you getting these errors? Is it when you try to run the local dev server?

**Comment by charlievoss** [comment]
Correct

**Comment by watzon** [comment]
I'll look into it, let me know if you figure anything out

**Comment by watzon** [comment]
@charlievoss Should be fixed. Let me know if you still experience issues
