### ISSUE TITLE
File tree explanation 

### ISSUE THREAD

**Issue by tylerzika** [iDev0urer/salesforce-angular2-boilerplate#9]
I have a basic understanding of how visualforce apps work. It would be nice if there was an explanation of each file in the file tree in the README.md. Just to see how Salesforce Angular2 Boilerplate fits in with Salesforce.

This would be especially helpful for Salesforce dev who are new to Angular.

**Comment by watzon** [comment]
Good idea!

**Comment by watzon** [comment]
I added a little bit of explanation to the README. Please let me know if there is anything that isn't clear
